name: Build Game and Create Download Link
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Manually Inject Missing Loader Files
        run: |
          rm -rf loader
          git clone --recursive https://github.com loader

      - name: Fix Workspace Configuration
        run: |
          echo "packages:" > pnpm-workspace.yaml
          echo "  - '.'" >> pnpm-workspace.yaml
          echo "  - 'frontend'" >> pnpm-workspace.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Restore Workload
        run: |
          cd loader
          dotnet workload restore --non-interactive
          cd ..

      - name: Build Game
        run: pnpm run build

      - name: Add Crucial Browser Security Headers
        run: |
          mkdir -p ./frontend/dist
          echo '{
            "headers": [
              {
                "source": "/(.*)",
                "headers": [
                  { "key": "Cross-Origin-Opener-Policy", "value": "same-origin" },
                  { "key": "Cross-Origin-Embedder-Policy", "value": "require-corp" }
                ]
              }
            ]
          }' > ./frontend/dist/vercel.json

      - name: Package Game Folder for Download
        uses: actions/upload-artifact@v4
        with:
          name: finished-celeste-game
          path: ./frontend/dist/
